apiVersion: v1
kind: ConfigMap
metadata:
  name: migrator-config
data:
  GOOSE_DRIVER: postgres
  # goose reads `PGSERVICEFILE` & `PGSERVICE`, as provided by 'pg-services'
  GOOSE_DBSTRING: postgres://
  GOOSE_MIGRATION_DIR: /migrations
