apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-migrations
data:
  wait.sh: |
    set -e
    while goose -no-color status 2>&1 | grep -q Pending
    do
        echo waiting for migrations to finish...
        sleep 10
    done
