kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgresql
  labels:
    app: postgresql
    kind: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgresql
          env:
          - name: POSTGRES_DB
            value: testing
          - name: POSTGRES_PASSWORD
            value: postgres
          volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
