apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
- pairs:
    app: oauth2-proxy
  includeSelectors: true

resources:
- config.yaml
- deployment.yaml
- ingress.yaml
- secrets.yaml
- service.yaml
