apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: baseproject-vault
    kind: SecretStore
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OAUTH2_PROXY_CLIENT_ID: "{{ .client_id }}"
        OAUTH2_PROXY_CLIENT_SECRET: "{{ .client_secret }}"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ .cookie_secret }}"
        OAUTH2_PROXY_OIDC_ISSUER_URL: "{{ .discovery_url }}"
  dataFrom:
  - extract:
      key: "set by kustzomize"
