apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config
  labels:
    pg-services: required
data:
  PGRST_DB_URI: postgresql://authenticator:null@/
  PGRST_DB_SCHEMA: api
  PGRST_DB_ANON_ROLE: anon
  PGRST_DB_EXTRA_SEARCH_PATH: public
  PGRST_LOG_LEVEL: "warn"
