---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  labels:
    kind: postgrest
    pg-services: required
    wait-for-migrations: required
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      annotations:
        fluentbit.io/parser-postgrest: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest
          envFrom:
          - configMapRef:
              name: postgrest-config
          readinessProbe:
            httpGet:
              path: /rpc/health
              port: 3000
          securityContext:
            runAsUser: 0        # must be able to read the certs
          env: []
          volumeMounts: []
      volumes: []
