---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  labels:
    kind: postgrest
    pg-services: required
    wait-for-migrations: required
    security-config: hardened
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      annotations:
        fluentbit.io/parser-postgrest: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest
          envFrom:
          - configMapRef:
              name: postgrest-config
          readinessProbe:
            httpGet:
              path: /rpc/health
              port: 3000
          securityContext:
            # must be able to read the certs -- 'security-config' replaces this
            # when included, and makes them group-readable via `fsGroup` instead
            runAsUser: 0
          env: []
          volumeMounts: []
