apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fsgroup.yaml
  target:
    kind: Deployment
    labelSelector: security-config=required
- path: fsgroup.yaml
  target:
    kind: Job
    labelSelector: security-config=required
- path: fsgroup-cronjob.yaml
  target:
    kind: CronJob
    labelSelector: security-config=required
- path: hardened.yaml
  target:
    kind: Deployment
    labelSelector: security-config=hardened
- path: hardened.yaml
  target:
    kind: Job
    labelSelector: security-config=hardened
- path: hardened-cronjob.yaml
  target:
    kind: CronJob
    labelSelector: security-config=hardened
