apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightwatch
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0       # no retries please
      template:
        metadata:
          labels:
            app: nightwatch
        spec:
          containers:
            - name: nightwatch
              image: nightwatch
              command:
              - "pipenv"
              - "run"
              - "pytest"
              - "--tb=native"
              - "--verbose"
              - "--browser-channel=chromium"
              - "--prometheus"
              - "--prometheus-pushgateway-url=http://pushgateway.cluster-infra.svc.cluster.local:9091/"
              args:
              - "--nightwatch-environment=staging"
          restartPolicy: Never
