---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nightwatch-helpers
data:
  run.sh: |
    if which uv > /dev/null; then
      run="uv run --no-sync"
    else
      run="pipenv run"
    fi

    while true
    do
      folder=nightwatch-zeit-de/$NIGHTWATCH_NAMESPACE/$NIGHTWATCH_ENVIRONMENT
      timestamp=$(date +%Y/%m/%d/%H-%M)
      echo "Nightwatch run $folder/$timestamp"
      rm -f /tmp/report.*

      if ! $run $@ --junitxml=/tmp/report.xml; then
          failure=1
      fi

      $run junit2html /tmp/report.xml /tmp/report.html
      $run gcs-upload /tmp/report.html gs://$folder/$timestamp.html
      if [[ $failure == 1 ]]; then
          $run gcs-upload /tmp/report.html gs://$folder/lastfailed.html
      fi

      sleep 4m
    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightwatch
spec:
  selector:
    matchLabels:
      app: nightwatch
  template:
    metadata:
      labels:
        app: nightwatch
      annotations:
        fluentbit.io/parser: zon-json-iso8601
        reloader.stakater.com/auto: "true"
    spec:
      serviceAccountName: baseproject
      securityContext:
        fsGroup: 10000 # make volumes readable by `app` user
      containers:
        - name: nightwatch
          image: nightwatch
          command:
          - "bash"
          - "/helpers/run.sh"
          - "pytest"
          - "--tb=native"
          - "--quiet"
          - "--show-capture=no"
          - "--prometheus"
          - "--prometheus-pushgateway-url=http://pushgateway.cluster-infra.svc.cluster.local:9091/"
          args:
          - "--nightwatch-environment=$NIGHTWATCH_ENVIRONMENT"
          volumeMounts:
          - name: nightwatch-helpers
            mountPath: /helpers
            readOnly: true
          - mountPath: /tmp # to support readOnlyRootFilesystem
            name: tmp
          env:
          - name: NIGHTWATCH_ENVIRONMENT
            value: staging
          - name: NIGHTWATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - secretRef:
              name: nightwatch-secrets
              optional: true
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
      volumes:
      - name: nightwatch-helpers
        configMap:
          name: nightwatch-helpers
      - name: tmp
        emptyDir:
          medium: Memory
