---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nightwatch-helpers
data:
  run.sh: |
    while true
    do
      folder=nightwatch-zeit-de/$NIGHTWATCH_NAMESPACE/$NIGHTWATCH_ENVIRONMENT
      timestamp=$(date +%Y/%m/%d/%H-%M)
      echo "Nightwatch run $folder/$timestamp"
      rm -f report.xml report.html

      if ! $@ --junitxml=report.xml then
          failure=1
      fi

      pipenv run junit2html report.xml report.html
      pipenv run gcs-upload report.html gs://$folder/$timestamp.html
      if [[ $failure == 1 ]]; then
          pipenv run gcs-upload report.html gs://$folder/lastfailed.html
      fi

      sleep 4m
    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightwatch
spec:
  selector:
    matchLabels:
      app: nightwatch
  template:
    metadata:
      labels:
        app: nightwatch
      annotations:
        fluentbit.io/parser: zon-json-iso8601
        reloader.stakater.com/auto: "true"
    spec:
      serviceAccountName: baseproject
      containers:
        - name: nightwatch
          image: nightwatch
          command:
          - "bash"
          - "/helpers/run.sh"
          - "pipenv"
          - "run"
          - "pytest"
          - "--tb=native"
          - "--quiet"
          - "--show-capture=no"
          - "--prometheus"
          - "--prometheus-pushgateway-url=http://pushgateway.cluster-infra.svc.cluster.local:9091/"
          args:
          - "--nightwatch-environment=$NIGHTWATCH_ENVIRONMENT"
          volumeMounts:
          - name: nightwatch-helpers
            mountPath: /helpers
            readOnly: true
          env:
          - name: NIGHTWATCH_ENVIRONMENT
            value: staging
          - name: NIGHTWATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - secretRef:
              name: nightwatch-secrets
              optional: true
      volumes:
      - name: nightwatch-helpers
        configMap:
          name: nightwatch-helpers
