apiVersion: v1
kind: ConfigMap
metadata:
  name: gcs-bucket-proxy
data:
  default.conf.template: |
    server {
      listen 80 default_server;
      access_log off;
      error_log /dev/stdout;
      location / {
        rewrite ^(.*)/$ $1/index.html break;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://${BUCKET_NAME}.storage.googleapis.com:80;
        proxy_http_version 1.1;
      }
    }
