apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-bucket-proxy
  labels:
    app: gcs-bucket-proxy
spec:
  selector:
    matchLabels:
      app: gcs-bucket-proxy
  template:
    metadata:
      labels:
        app: gcs-bucket-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: gcs-bucket-proxy
          mountPath: /etc/nginx/templates
      volumes:
      - name: gcs-bucket-proxy
        configMap:
          name: gcs-bucket-proxy
